version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server --console-address ":9090" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3